"""create table cars

Revision ID: 5010c586af5b
Revises: 
Create Date: 2022-02-28 16:54:48.102929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5010c586af5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_cars',
    sa.Column('chassi', sa.String(), nullable=False),
    sa.Column('license_plate', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('color_car', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('current_km', sa.Float(), nullable=False),
    sa.Column('licensing_expiration', sa.DateTime(), nullable=False),
    sa.Column('daily_rental_price', sa.Float(), nullable=False),
    sa.Column('daily_fixed_km', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('chassi'),
    sa.UniqueConstraint('license_plate')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_cars')
    # ### end Alembic commands ###
